# Generated by Django 6.0.6 on 2026-06-16 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=50)),
                ('event_type', models.CharField(blank=True, help_text='The raw event header or type identifier.', max_length=255, null=True)),
                ('raw_payload', models.JSONField(help_text='Full, untampered raw body content received from the payment gateway.')),
                ('order_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Extracted order ID from the payload.', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Tracks whether the signal handler executed successfully.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhooks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(help_text="The app where the model belongs (e.g., 'core', 'payments').", max_length=100)),
                ('model_name', models.CharField(help_text='The target database table name.', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='Primary key identifier of the modified row.')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão')], max_length=10)),
                ('changes_payload', models.JSONField(help_text='Key-value mapping of modified field states.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria Geral',
                'verbose_name_plural': 'Logs de Auditoria Geral',
                'ordering': ['-timestamp'],
            },
        ),
    ]
